#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions

clear
echo "//---------------------------------------------------------------------//"
echo "Cap nhat Phpmyadmin"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-23-61"
echo "/-----------------------------------------------------------------------/"
echo

phpmyadmin_version=5.2.1
cd /usr/share/nginx/larvps
wget https://files.phpmyadmin.net/phpMyAdmin/$phpmyadmin_version/phpMyAdmin-$phpmyadmin_version-all-languages.zip
unzip phpMyAdmin-$phpmyadmin_version-all-languages.zip
mv phpMyAdmin-$phpmyadmin_version-all-languages phpmyadmin
rm -f phpMyAdmin-$phpmyadmin_version-all-languages.zip
cp /usr/share/nginx/larvps/phpmyadmin/config.sample.inc.php  /usr/share/nginx/larvps/phpmyadmin/config.inc.php
secret=$(openssl rand -base64 32)
echo "\$cfg['TempDir'] = '/var/lib/phpmyadmin/tmp';" >> /usr/share/nginx/larvps/phpmyadmin/config.inc.php
echo "\$cfg['blowfish_secret'] = '$secret';" >> /usr/share/nginx/larvps/phpmyadmin/config.inc.php
mkdir -p /var/lib/phpmyadmin/tmp
chmod 700 /var/lib/phpmyadmin/tmp
chown nginx:nginx /var/lib/phpmyadmin/tmp
chown -hR nginx:nginx /usr/share/nginx/larvps/phpmyadmin

sleep 3
clear
echo "Da cap nhat Phpmyadmin 5.2.1"

action_larvps_update