#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "-------------------------------------------------------------------------"
echo "Cap nhat he thong"
echo "-------------------------------------------------------------------------"
echo ""
read -p "Xac nhan cap nhat he thong (y/n): " confirm
if [[ "$confirm" = 'y' ]]; then

    cat >> /etc/yum.repos.d/mariadb.repo<<EOF
[mariadb]
name = MariaDB
baseurl = https://yum.mariadb.org/10.5/centos8-amd64
module_hotfixes=1
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
EOF



sudo dnf install epel-release -y
sudo dnf upgrade -y
    clear
    echo "Hoan thanh..."
    action_larvps_update
fi
action_larvps_update