#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "//---------------------------------------------------------------------//"
echo "Thay doi phien ban PHP - Hien tai: v$(php -v | head -n 1 | cut -d " " -f 2)"
echo "/-----------------------------------------------------------------------/"
echo
PS3='
Nhap lua chon (1-3) [0=Thoat]: '
options=("8.2" "8.1" "8.0" "7.4")
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/php_manager/php82'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/php_manager/php81'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/php_manager/php80'
            ;;
        "${options[3]}")
            '/etc/larvps/menu/action/php_manager/php74'
            ;;
        *) larvps;;
    esac
done

