#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Thay doi co che PHP"
echo "-------------------------------------------------------------------------"
echo ""
echo "Neu VPS ban nhieu RAM/CPU cao thi chon Dynamic cho cac domain. Max Child tang từ 20 - 100 tuy nhu cau thuc te su dung:"