#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Xem Access Log cua domain"
echo "-------------------------------------------------------------------------"
echo ""

choose_domain

if [ "$domain" = "" ]; then
    clear
    echo "Bạn chưa nhập Domain."
    echo
    action_nginx_manager
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain bạn nhập không đúng định dạng."
    echo
    action_nginx_manager
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain không tồn tại trên VPS."
    echo
    action_nginx_manager
fi

username=$(get_user $domain)

if [[ ! -f "/etc/nginx/conf.d/cloudflare.conf" ]]; then
    
CLOUDFLARE_FILE_PATH=/etc/nginx/conf.d/cloudflare.conf

echo "#Cloudflare" > $CLOUDFLARE_FILE_PATH;
echo "" >> $CLOUDFLARE_FILE_PATH;

echo "# - IPv4" >> $CLOUDFLARE_FILE_PATH;
for i in `curl https://www.cloudflare.com/ips-v4`; do
    echo "set_real_ip_from $i;" >> $CLOUDFLARE_FILE_PATH;
done

echo "" >> $CLOUDFLARE_FILE_PATH;
echo "# - IPv6" >> $CLOUDFLARE_FILE_PATH;
for i in `curl https://www.cloudflare.com/ips-v6`; do
    echo "set_real_ip_from $i;" >> $CLOUDFLARE_FILE_PATH;
done

echo "" >> $CLOUDFLARE_FILE_PATH;
echo "real_ip_header CF-Connecting-IP;" >> $CLOUDFLARE_FILE_PATH;
fi


sed -i "s/#access_log/access_log/" "/etc/nginx/conf.d/$domain.conf"
sed -i "s/access_log off/access_log on/" "/etc/nginx/conf.d/$domain.conf"

restart_nginx

if [[ ! -f "/home/$username/$domain/logs/access.log" ]]; then
clear
echo "Hien tai access log cho ghi nhan IP nao truy cap vao web. "
action_nginx_manager
fi
watch tail -30 "/home/$username/$domain/logs/access.log"