#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Chan IP bang Nginx"
echo "-------------------------------------------------------------------------"
echo ""
echo "Hướng dẫn:"
echo "- Sau khi thay đổi gõ larvps nginx -r để khởi động lại Nginx"
echo "- Ctrl + X hoặc Ctrl + 0 chọn Y: Để lưu lại thay đổi cấu hình."
echo "Đang chuẩn bị mở cấu hình cho referrer_spam.conf..."
echo
echo "Luu Y: Khoi dong lai Nginx sau khi them"
sleep 5
nano /etc/nginx/conf.d/deny_ip.conf