#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Chan Referrer spam cho domain"
echo "-------------------------------------------------------------------------"

choose_domain

if [ "$domain" = "" ]; then
    clear
    echo "Bạn chưa nhập Domain."
    echo
    action_nginx_manager
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain bạn nhập không đúng định dạng."
    echo
    action_nginx_manager
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain không tồn tại trên VPS."
    echo
    action_nginx_manager
fi

username=$(get_user $domain)

cat > "/home/$username/$domain/public_html/referer_domain.conf" <<END
if (\$bad_referer) {
    return 444;
}
END

restart_nginx

echo "Ban co the Redirect trong file cau hinh tai: /home/$username/$domain/public_html/referer_domain.conf"
echo "Vi du: return 301 https://google.com; thay cho return 444;"
echo "Xoa file neu muon xoa Referrer spam."

sleep 5

action_nginx_manager