#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
type=$1
domain=$2
email=$3
key=$4
phone=$5
name=$6
username=${domain//[-._]/}

mkdir -p "/home/${username}/${domain}/public_html/.well-known/pki-validation"


if [[ ! -f '/usr/bin/jq' ]]; then
   yum install jq -y
fi

#dhparam
if [[ ! -f /etc/ssl/certs/dhparam.pem ]]; then
echo "Dang them dhparam, vui long doi, viec nay ton kha nhieu thoi gian, va chi lam 1 lan duy nhat."
openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
echo "hoan thanh"
clear
fi

mkdir -p "/home/${username}/${domain}/public_html/.well-known/pki-validation"
echo -e "larvps" > /home/${username}/${domain}/public_html/.well-known/pki-validation/text.txt


laravel=0
#check Laravel
if [[ -f /home/${username}/${domain}/public_html/public/index.php ]]; then
laravel=1
echo -e "larvps" > /home/${username}/${domain}/public_html/public/.well-known/pki-validation/text.txt
fi

# statusCode=$(curl -H 'Pragma: no-cache' --write-out %{http_code} --silent --output /dev/null "http://${domain}/.well-known/pki-validation/text.txt")
# if [ "$statusCode" == "301" ]; then
# statusCode=$(curl -H 'Pragma: no-cache' --write-out %{http_code} --silent --output /dev/null "https://${domain}/.well-known/pki-validation/text.txt")
# fi

# if [ "$statusCode" != "200" ]; then
# username=${domain//[-._]/}
# port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
# . /etc/larvps/menu/action/domain/template/nginx $domain $username $port_listen
# restart_nginx
# statusCode=$(curl -H 'Pragma: no-cache' --write-out %{http_code} --silent --output /dev/null "http://${domain}/.well-known/pki-validation/text.txt")
# fi

# if [ "$statusCode" != "200" ]; then
# echo "Khong the cai duoc Paid SSL."
# exit 1
# fi


echo "Dang tien hanh cap SSL"
curl --location --silent --request POST 'https://my.larvps.com/api/v1/ssl/order' \
--form "type=$type" \
--form "key=$key" \
--form "domain=$domain" \
--form "email=$email" \
--form "name=$name" \
--form "phone=$phone" -o /home/${username}/${domain}/ssl/${domain}.txt

type=$(cat /home/${username}/${domain}/ssl/${domain}.txt | jq ".type" | tr -d '"')
message=$(cat /home/${username}/${domain}/ssl/${domain}.txt | jq ".message" | tr -d '"')
waiting=$(cat /home/${username}/${domain}/ssl/${domain}.txt | jq ".waiting" | tr -d '"')
status=$(cat /home/${username}/${domain}/ssl/${domain}.txt | jq ".status" | tr -d '"')
orderId=$(cat /home/${username}/${domain}/ssl/${domain}.txt | jq ".orderId" | tr -d '"')
csrKey=$(cat /home/${username}/${domain}/ssl/${domain}.txt | jq ".csr_key" | tr -d '"')


# truong hop cap thanh cong
if [[ "$status" = "1" ]]; then
    curl --silent --location --request GET "https://my.larvps.com/api/v1/ssl/order/${orderId}" -o "/home/${username}/${domain}/ssl/${domain}_crt.txt"
    echo -e $csrKey > /home/${username}/${domain}/ssl/${domain}.key
else

    fileName=$(cat /home/${username}/${domain}/ssl/${domain}.txt | jq ".data .fileName" | tr -d '"')
    content=$(cat /home/${username}/${domain}/ssl/${domain}.txt | jq ".data .content" | tr -d '"')
    orderId=$(cat /home/${username}/${domain}/ssl/${domain}.txt | jq ".data .orderId" | tr -d '"')
    csrKey=$(cat /home/${username}/${domain}/ssl/${domain}.txt | jq ".data .csrKey" | tr -d '"')

    echo -e "$content" > /home/${username}/${domain}/public_html/.well-known/pki-validation/${fileName}
    if [[ -f /home/${username}/${domain}/public_html/public/index.php ]]; then
        echo -e "$content" > /home/${username}/${domain}/public_html/public/.well-known/pki-validation/${fileName}
    fi
    echo -e $csrKey > /home/${username}/${domain}/ssl/${domain}.key

    if [[ ! -f /home/${username}/${domain}/public_html/.well-known/pki-validation/${fileName} ]]; then
    echo "Khong tim thay file xac thuc..."
    sleep 5 
    exit 1
    fi

    for i in {1..300}; do
        type=$(curl --silent --location --request GET "https://my.larvps.com/api/v1/ssl/order/${orderId}" | jq ".type" | tr -d '"')
        echo $type
        if [[ "$type" == "success" ]]; then
            curl --silent --location --request GET "https://my.larvps.com/api/v1/ssl/order/${orderId}" -o "/home/${username}/${domain}/ssl/${domain}_crt.txt"
            break   
        fi
    done
fi

crtCode=$(cat /home/${username}/${domain}/ssl/${domain}_crt.txt | jq ".data .crt_code" | tr -d '"')
caCode=$(cat /home/${username}/${domain}/ssl/${domain}_crt.txt | jq ".data .ca_code" | tr -d '"')
endAt=$(cat /home/${username}/${domain}/ssl/${domain}_crt.txt | jq ".data .end_date" | tr -d '"')
activatedAt=$(cat /home/${username}/${domain}/ssl/${domain}_crt.txt | jq ".data .begin_date" | tr -d '"')


echo -e $csrKey > /home/${username}/${domain}/ssl/${domain}.key
echo -e "$crtCode$caCode" > "/home/${username}/${domain}/ssl/${domain}.crt"

mkdir -p /home/$username/$domain/ssl

cat > "/home/$username/$domain/ssl/$domain.conf" <<END
ssl_certificate /home/$username/$domain/ssl/$domain.crt;
ssl_certificate_key /home/$username/$domain/ssl/$domain.key;
ssl_session_cache shared:SSL_PAID:10m;
ssl_session_timeout  100m;
ssl_ciphers EECDH+AESGCM:EDH+AESGCM;
ssl_ecdh_curve secp384r1;
ssl_prefer_server_ciphers on;
ssl_session_tickets off;
resolver 8.8.8.8 valid=300s;
resolver_timeout 5s;
ssl_dhparam /etc/ssl/certs/dhparam.pem;
END
echo


crtCode=$(cat /home/${username}/${domain}/ssl/${domain}.crt)

if [[ "$key" != "" || "$status" != "1" ]]; then
curl --silent --location --request POST "https://my.larvps.com/api/v1/ssl/order/${orderId}/success" \
--form "activated_at=$activatedAt" \
--form "end_at=$endAt" \
--form "crt_code=$crtCode"
fi

#restore nginx
rm -rf /etc/nginx/conf.d/$domain.conf
username=${domain//[-._]/}
port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
if [[ "$laravel" = "1" ]]; then
. /etc/larvps/menu/action/domain/template/nginx_paid_ssl_laravel $domain $username $port_listen
else
. /etc/larvps/menu/action/domain/template/nginx_paid_ssl $domain $username $port_listen
fi
restart_nginx   
