#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "21. Thiep lap Paid SSL >  Redirect 301"
echo "/-----------------------------------------------------------------------/"
echo

nginx="$(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"

if [[ "$nginx" != "active" ]]; then
    clear
    echo "Nginx hien tai khong hoat dong. Vui long kiem tra lai."
    echo
    action_ssl_manager
fi

choose_domain

if [ "$domain" = "" ]; then
    clear
    echo "Ban chua nhap Domain."
    echo
    action_ssl_manager
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain ban nhap khong dung dinh dang."
    echo
    action_ssl_manager
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    echo
    action_ssl_manager
fi
username=${domain//[-._]/}

read -p "Nhap domain ban muon Redirect: " domain_redirect

. /etc/larvps/menu/action/domain/template/nginx_paid_ssl_redirect $domain $username $domain_redirect

restart_nginx
echo
action_ssl_manager