#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear

if [[ ! -f "/etc/larvps/menu/mod_security" ]]; then
count=$(ls -A /etc/larvps/user/ | wc -l)
if [[ "$count" -gt "0" ]]; then
clear
echo "/------------------------------------------------------------------------/"
echo "Ban dang dung phien ban Free, chi ho tro 1 ten mien."
echo "Nang cap: https://larvps.com/pages/pricing"
echo "/------------------------------------------------------------------------/"
sleep 3 
action_domain
fi
fi


echo "--//---------------------------------------------------------------------"
echo "1. Quan ly Domain > Alias"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-5-3"
echo "/-----------------------------------------------------------------------/"
echo

nginx="$(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
if [[ "$nginx" != 'active' ]]; then
clear
echo "-------------------------------------------------------------------------"
echo "Co loi xay ra:"
echo "-------------------------------------------------------------------------"
echo "Vui long kiem tra các service truoc khi them ten mien:"
echo "/------------------------------------------------------------------------/"
echo "Nginx: $nginx"
echo "/------------------------------------------------------------------------/"
sleep 3
action_domain 
fi

domain=$1
if [ -z "$domain" ]; then
read -p "Nhap domain hoac subdomain ban muon them 
    (vidu: larvps.com, abc.larvps.com) [0=Thoat]: " domain_alias
fi


if [[ "$domain_alias" = "0" ]]; then
    clear
    action_domain
fi

if [ "$domain_alias" = '' ]; then
    clear
    echo "Ban chua nhap Domain."
    echo
    action_domain
fi

if [ "$domain_alias" = "${domain_alias/.}" ]; then
    clear
    echo "Domain ban nhap khong dung dinh dang."
    echo
    action_domain
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain_alias.conf"
if [[ -f "$path" ]]; then
    clear
    echo "Domain da ton tai tren VPS."
    echo
    action_domain
fi


read -p "Nhap domain ban muon Alias: " domain

if [[ "$domain" = "0" ]]; then
    clear
    action_domain
fi

if [ "$domain" = '' ]; then
    clear
    echo "Ban chua nhap Domain."
    echo
    action_domain
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain ban nhap khong dung dinh dang."
    echo
    action_domain
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain $domain khong ton tai tren VPS."
    echo
    action_domain
fi
# read -p "Ban co muon cai dat SSL (Let's Encrypt) ?  
# Yeu cau: Domain da tro IP ve VPS. (y/n): " confirm_ssl
# echo

# Tạo user và đổi pass
# useradd $username


#config nginx
# cat > "/etc/nginx/conf.d/$domain.conf" <<END
# server {
#     listen 80;
#     server_name www.$domain;
#     return 301 \$scheme://$domain\$request_uri;
# }
# END

#alias config
# for line in `grep -n "server_name" /etc/nginx/conf.d/$domain_alias.conf | grep  -v "www" | cut -f1 -d":"`; do
# sed -i "${line}s/server_name/& $domain/" /etc/nginx/conf.d/$domain_alias.conf
# done
username=${domain//[-._]/}
port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
echo /etc/larvps/menu/action/domain/template/nginx_alias $domain ${domain_alias} $username $port_listen
. /etc/larvps/menu/action/domain/template/nginx_alias $domain ${domain_alias} $username $port_listen
restart_nginx

# lưu config user
cat > "/etc/larvps/user/.$domain_alias.conf" <<END
[$domain_alias]
username=$username
domain=$domain_alias
domain_alias=$domain
type=alias
END

#cai dat ssl
# if [ "$confirm_ssl" = "y" ]; then
# . /etc/larvps/menu/action/lets_encrypt/create $domain
# fi

# restart_nginx

clear
echo
echo "Cam on ban da su dung LarVPS"
echo "Ban da them domain thanh cong. Hay luu lai thong tin de su dung ve sau"
echo "-------------------------------------------------------------------------"
echo "1.  Domain                : $domain"
echo "2.  Redirect              : $domain_alias"
echo "-------------------------------------------------------------------------"
echo
action_domain