#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "//---------------------------------------------------------------------//"
echo "1. Quan ly Domain  > Xoa SubFolder"
echo "-------------------------------------------------------------------------"
echo ""


read -p "Nhap ten sub folder (khong dau/viet lien): " folder

echo "Chon Domain chua sub folder"

choose_domain

if [ "$domain" = '' ]; then
    clear
    echo "Bạn chưa nhập Domain."
    echo
    action_application
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain bạn nhập không đúng định dạng."
    echo
    action_application
fi

username=$(get_user $domain)
rm -rf /home/${username}/${domain}/public_html/${folder}-nginx.conf
rm -rf /home/${username}/${domain}/public_html/${folder}
clear
sleep 3
echo "Da xoa subfolder thanh cong"

restart_nginx
action_domain