#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "//---------------------------------------------------------------------//"
echo "1. Quan ly Domain  > Cai dat SubFolder"
echo "-------------------------------------------------------------------------"
echo ""


db_name=""
db_user=""
db_password=""


read -p "Nhap ten sub folder (khong dau/viet lien): " folder


echo "Chon Domain chua sub folder"

choose_domain

if [ "$domain" = '' ]; then
    clear
    echo "Bạn chưa nhập Domain."
    echo
    action_application
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain bạn nhập không đúng định dạng."
    echo
    action_application
fi

username=$(get_user $domain)
mkdir -p "/home/${username}/${domain}/public_html/${folder}"

cat > "/home/${username}/${domain}/public_html/${folder}-nginx.conf" <<END
location /${folder}/ {
            try_files \$uri \$uri/ /${folder}/index.php?\$args; 
}
END

chown -hR $username:$username /home/$username/$domain/public_html/${folder}
chmod -R a=r,u+w,a+X /home/$username/$domain/public_html/${folder}
restart_nginx

read -p "Ban co muon cai dat WP trong subfolder ${huynhtong}: (y/n)" confirm_wp


if [[ "$confirm_wp" == 'y' ]]; then

c_db_name=$(< /dev/urandom tr -dc a-z | head -c${1:-8};echo;)
db_name=${c_db_name}_db
db_user=${c_db_name}_user
db_password=$(< /dev/urandom tr -dc a-z0-9 | head -c${1:-24};echo;)

rm -rf /home/$username/$domain/public_html/${folder}/*

# create db
mysql -u admin -p"$db_admin_password" -e "DROP DATABASE IF EXISTS ${db_name}"
mysql -u admin -p"$db_admin_password" -e "CREATE DATABASE IF NOT EXISTS ${db_name}"
mysql -u admin -p"$db_admin_password" -e "CREATE USER IF NOT EXISTS '$db_user'@'localhost' IDENTIFIED BY '$db_password'"
mysql -u admin -p"$db_admin_password" -e "GRANT ALL PRIVILEGES ON ${db_name}.* TO '$db_user'@'localhost'"
mysql -u admin -p"$db_admin_password" -e "FLUSH PRIVILEGES"

cd
curl -O https://wordpress.org/latest.tar.gz
tar -zxvf latest.tar.gz
cd wordpress
cp -rf . /home/$username/$domain/public_html/${folder}
cd ..
rm -rf wordpress
rm -rf latest.tar.gz

cd /home/$username/$domain/public_html/${folder}

#set WP salts
SALT=$(curl -L https://api.wordpress.org/secret-key/1.1/salt/)

cat > "/home/$username/$domain/public_html/${folder}/wp-config.php" <<END
<?php
define('DISALLOW_FILE_EDIT', true);
define( 'WP_MEMORY_LIMIT', '128M' );
define( 'WP_CACHE', true );
define('FS_METHOD', 'direct');
define( 'DB_NAME', '$db_name' );
define( 'DB_USER', '$db_user' );
define( 'DB_PASSWORD', '$db_password' );
define( 'DB_HOST', 'localhost' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );
define('DISABLE_WP_CRON', false);

$SALT

\$table_prefix = "${prefix}_";

define( 'WP_DEBUG', false );

if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', dirname( __FILE__ ) . '/' );
}
require_once( ABSPATH . 'wp-settings.php' );

END

#create robots
cat > "/home/$username/$domain/public_html/${folder}/robots.txt" <<END
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php
END

# set chown
chown -R $username:$username /home/$username/$domain/public_html/${folder}
chmod -R a=r,u+w,a+X /home/$username/$domain/public_html/${folder}
chmod 0400 /home/$username/$domain/public_html/${folder}/wp-config.php
rm -rf /home/$username/$domain/public_html/${folder}/readme.html
rm -rf /home/$username/$domain/public_html/${folder}/license.txt

fi

clear
sleep 3
echo '----------------'
echo "Da thiet lap thanh cong"
echo "http://${domain}/${folder}"
if [[ "$confirm_wp" == 'y' ]]; then
echo "DB name: ${db_name}"
echo "DB username: ${db_name}"
echo "DB password: ${db_password}"
fi
echo '----------------'
action_domain



