#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//-------------------------------------------------------------------//"
echo "1. Quan ly Domain > Chay Domain bang IP"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-5"
echo "/-----------------------------------------------------------------------/"
echo

echo "Chon Domain"

choose_domain

if [ "$domain" = '' ]; then
    clear
    echo "Bạn chưa nhập Domain."
    echo
    action_domain
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain bạn nhập không đúng định dạng."
    echo
    action_domain
fi

username=$(get_user $domain)
port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")

. /etc/larvps/menu/action/domain/template/nginx_default_ip $domain $username $port_listen

restart_nginx
clear
sleep 3
echo "Da thiet lap thanh cong"

action_domain

