#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "2. Quan ly Let's Encrypt > Cap lai toan bo Let's Encrypt ACME"
echo "-------------------------------------------------------------------------"
echo "Huong dan: "
echo "/-----------------------------------------------------------------------/"
echo

/root/.acme.sh/acme.sh --set-default-ca --server letsencrypt

for entry in `ls -A /etc/larvps/user`; do
    domain=$( echo $entry | sed 's/^.//' | sed 's/\.conf//')
    username=$(get_user "$domain")

    # check paid ssl
    if [[ ! -f "/home/$username/$domain/ssl/$domain.conf" ]]; then
            
            # restore nginx
            rm -rf /etc/nginx/conf.d/$domain.conf
            username=${domain//[-._]/}
            port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
            . /etc/larvps/menu/action/domain/template/nginx $domain $username $port_listen
            restart_nginx

            mkdir -p "/home/$username/$domain/public_html/.well-known/acme-challenge"

            is_subdomain ${domain}
            if [[  "${IS_SUBDOMAIN}" = "n" ]]; then
                /root/.acme.sh/acme.sh --issue -d ${domain} -d www.${domain} --nginx --force
            else
                /root/.acme.sh/acme.sh --issue -d ${domain} --nginx --force
            fi

            if [[ -f "/root/.acme.sh/${domain}/fullchain.cer" ]]; then
                . /etc/larvps/menu/action/domain/template/nginx_acme $domain $username $port_listen
            fi
            
     fi 
    
    
    
   

 done

 restart_nginx