#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "2. Quan ly Let's Encrypt > Redirect 301"
echo "-------------------------------------------------------------------------"
echo "Huong dan: "
echo "/-----------------------------------------------------------------------/"
echo

echo
choose_domain

if [ "$domain" = "" ]; then
    clear
    echo "Ban chua nhap Domain."
    echo
        action_lets_encrypt

fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain ban nhap khong dung dinh dang."
    echo
        action_lets_encrypt

fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    echo
        action_lets_encrypt

fi

username=${domain//[-._]/}

read -p "Nhap domain ban muon Redirect: " domain_redirect

. /etc/larvps/menu/action/domain/template/nginx_lets_redirect $domain $username $domain_redirect

restart_nginx
`   
echo
action_lets_encrypt
