#!/bin/bash
domain=$1
username=$2
domain_redirect=$3

cat > "/etc/nginx/conf.d/$domain.conf" <<END
server {
    listen 80;

    server_name www.$domain $domain;

    location ^~ /.well-known/pki-validation/ {
        allow all;
        default_type "text/plain";
    }

    location ~ /.well-known/acme-challenge/ {
        allow all;
        root /usr/share/nginx/html;
    }

    return 301 https://$domain_redirect\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name www.$domain $domain;

    location ^~ /.well-known/pki-validation/ {
        allow all;
        default_type "text/plain";
    }

    location ~ /.well-known/acme-challenge/ {
        allow all;
        root /usr/share/nginx/html;
    }
    
    include /home/$username/$domain/ssl/$domain.conf;
    
    return 301 https://$domain_redirect\$request_uri;
}
END