#!/bin/bash
if [[ ! -f "/etc/nginx/ssl/nginx.crt" ]]; then
   mkdir -p /etc/nginx/ssl
    openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
        
    expect -c "
    spawn sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt
    expect \"letter\"
    send \"VN\r\"
    expect \"full\"
    send \"Nginx\r\"
    expect \"city\"
    send \"Nginx\r\"
    expect \"company\"
    send \"Nginx\r\"
    expect \"Name\"
    send \"Nginx\r\"
    expect \"Name\"
    send \"Nginx\r\"
    expect \"Address\"
    send \"nginx@gmail.com\r\"
    expect eof
    "
fi

cat > "/etc/nginx/conf.d/default.conf" <<END

server {
    server_name _;
    listen 80 default_server;

    location ^~ /.well-known/pki-validation/ {
        allow all;
        default_type "text/plain";
    }
    
    location ~ /.well-known/acme-challenge/ {
        allow all;
        root /usr/share/nginx/html;
    }
    
    return 404;
}

server {
    listen 443 ssl default_server;
    server_name _;

    location ^~ /.well-known/pki-validation/ {
        allow all;
        default_type "text/plain";
    }
    
    location ~ /.well-known/acme-challenge/ {
        allow all;
        root /usr/share/nginx/html;
    }

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_session_tickets off;
    return 404;
}


server {
    listen 6789;
    server_name larvps;
    root /usr/share/nginx/larvps;

    auth_basic "Restricted";
    auth_basic_user_file /usr/share/nginx/larvps/passwd/.htpasswd;

    index index.php index.html index.htm;
    location / {
         try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location ~ \.php$ {
        try_files \$uri =404;
        fastcgi_intercept_errors on;
        fastcgi_index  index.php;
        fastcgi_connect_timeout 1000;
        fastcgi_send_timeout 1000;
        fastcgi_read_timeout 1000;
        fastcgi_buffer_size 256k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME  \$document_root\$fastcgi_script_name;
        fastcgi_pass unix:/run/php-fpm/www.sock;
    }
}
END