#!/bin/bash
domain=$1
username=$2
domain_redirect=$3
PATH_CER="/root/.acme.sh/${domain}_ecc/fullchain.cer"
PATH_KEY="/root/.acme.sh/${domain}_ecc/${domain}.key"

cat > "/etc/nginx/conf.d/$domain.conf" <<END
server {
    listen 80;

    server_name www.${domain} ${domain};

    location ^~ /.well-known/pki-validation/ {
        allow all;
        default_type "text/plain";
    }

    location ~ /.well-known/acme-challenge/ {
        allow all;
        root /usr/share/nginx/html;
    }

    return 301 https://${domain_redirect}\$request_uri;

}

server {
    listen 443 ssl http2;
    server_name www.$domain $domain;

    location ^~ /.well-known/pki-validation/ {
        allow all;
        default_type "text/plain";
    }

    location ~ /.well-known/acme-challenge/ {
        allow all;
        root /usr/share/nginx/html;
    }

    
    ssl_certificate ${PATH_CER};
    ssl_certificate_key ${PATH_KEY};
    include /etc/nginx/ssl_config.conf;
    
    return 301 https://$domain_redirect\$request_uri;
}

END