#!/bin/bash
domain=$1
username=$2
port_listen=$3

cat > "/etc/php-fpm.d/$domain.conf" <<END
[$domain]
listen = 127.0.0.1:$port_listen
user = $username
group = $username
listen.mode = 644
listen.allowed_clients = 127.0.0.1
pm = ondemand
pm.max_children = 20
pm.process_idle_timeout=10s
php_admin_value[open_basedir] = /home/$username/$domain:/tmp
php_admin_value[upload_tmp_dir] = /home/$username/$domain/tmp:/tmp
php_admin_value[session.safe_path] = /home/$username/$domain/session
php_admin_value[error_log] = /home/$username/$domain/logs/php_error_log.log
php_admin_value[session.save_path] = /home/$username/$domain/session
php_admin_value[request_slowlog_timeout] = 6s
php_admin_value[slowlog] = /home/$username/$domain/logs/php_slowlog.log
php_admin_value[log_errors] = on
END