#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions


domain=$1
username=${domain//[-._]/}

if [[ ! -f '/usr/bin/jq' ]]; then
   yum install jq -y
fi

#dhparam
if [[ ! -f /etc/nginx/ssl/dhparam.pem ]]; then
echo "Dang them dhparam, vui long doi, viec nay ton kha nhieu thoi gian, va chi lam 1 lan duy nhat."
openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
echo "hoan thanh"
clear
fi


if [[ ! -f /etc/nginx/ssl_config.conf ]]; then
cat > "/etc/nginx/ssl_config.conf" <<END
ssl_session_cache shared:SSL_LET:10m;
ssl_session_timeout  10m;
ssl_ciphers EECDH+AESGCM:EDH+AESGCM;
ssl_ecdh_curve secp384r1;
ssl_prefer_server_ciphers on;
ssl_session_tickets off;
resolver 8.8.8.8 valid=300s;
resolver_timeout 5s;
ssl_dhparam /etc/nginx/ssl/dhparam.pem;
END
fi


# restore nginx
rm -rf /etc/nginx/conf.d/$domain.conf
username=${domain//[-._]/}
port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
. /etc/larvps/menu/action/domain/template/nginx $domain $username $port_listen
restart_nginx


laravel=0
#check Laravel
if [[ -f /home/${username}/${domain}/public_html/public/index.php ]]; then
laravel=1
fi

mkdir -p /etc/nginx/zerossl/${domain}/conf
rm -rf /etc/nginx/zerossl/${domain}/conf/*
cd /etc/nginx/zerossl/${domain}/conf

mkdir -p "/home/${username}/${domain}/public_html/.well-known/pki-validation"
echo -e "larvps" > /home/${username}/${domain}/public_html/.well-known/pki-validation/text.txt

if [[ -d "/home/${username}/${domain}/public_html/public" ]]; then
mkdir -p "/home/${username}/${domain}/public_html/public/.well-known/pki-validation"
echo -e "larvps" > /home/${username}/${domain}/public_html/public/.well-known/pki-validation/text.txt
fi

# statusCode=$(curl -H 'Pragma: no-cache' --write-out %{http_code} --silent --output /dev/null "http://${domain}/.well-known/pki-validation/text.txt")
# if [ "$statusCode" == "301" ]; then
# statusCode=$(curl -H 'Pragma: no-cache' --write-out %{http_code} --silent --output /dev/null "https://${domain}/.well-known/pki-validation/text.txt")
# fi

# if [ "$statusCode" != "200" ]; then
# username=${domain//[-._]/}
# port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
# . /etc/larvps/menu/action/domain/template/nginx $domain $username $port_listen
# /bin/systemctl restart nginx
# statusCode=$(curl -H 'Pragma: no-cache' --write-out %{http_code} --silent --output /dev/null "http://${domain}/.well-known/pki-validation/text.txt")
# fi

# if [ "$statusCode" != "200" ]; then
# clear
# echo "1.1 Khong the cai duoc ZeroSSL cho ${domain}. Vui long kiem tra Domain da tro ve VPS chua ban nhe."
# sleep 5
# exit 1
# fi

echo "Dang tien hanh cap SSL cho domain: ${domain}"
curl --silent --location --request POST 'https://my.larvps.com/api/v1/zerossl' --form "domain=${domain}" -o order.txt

fileName=$(cat order.txt | jq ".data .fileName" | tr -d '"')
content=$(cat order.txt | jq ".data .content" | tr -d '"')
csrKey=$(cat order.txt | jq ".data .csrKey" | tr -d '"')
orderId=$(cat order.txt | jq ".data .orderId" | tr -d '"')
csrCode=$(cat order.txt | jq ".data .csrCode" | tr -d '"')
domainOrder=$(cat order.txt | jq ".data .domain" | tr -d '"')
expires=$(cat order.txt | jq ".data .expires" | tr -d '"')
orderId=$(cat order.txt | jq ".data .orderId" | tr -d '"')
status=$(curl --silent --location --request GET "https://my.larvps.com/api/v1/zerossl/order-status/${orderId}" | jq ".status" | tr -d '"')

echo "ID: ${orderId}"

if [[ "$status" == "issued" ]]; then
    #download
    curl --silent --location --request GET "https://my.larvps.com/api/v1/zerossl/${orderId}/download" -o download.txt
    clear
    echo "Da cap thanh cong cho domain: ${domain}".
else 

if [[ -f /home/${username}/${domain}/public_html/.well-known/pki-validation/${fileName} ]]; then
    clear
    echo
    echo "Ban vui long doi trong 30 phut roi cap lai, ZeroSSL da ghi nhan dang ky domain cua ban."
    echo "Trong thoi gian cho doi. Ban co the cap Let's Encrypt o module 31.2 de site co the hoat dong binh thuong."
    sleep 15
    exit 1
fi


# Cấp mới
echo -e $content > /home/${username}/${domain}/public_html/.well-known/pki-validation/${fileName}
if [[ -d "/home/${username}/${domain}/public_html/public" ]]; then
echo -e $content > /home/${username}/${domain}/public_html/public/.well-known/pki-validation/${fileName}
fi

statusFilename=$(curl --write-out %{http_code} --silent --output /dev/null "http://${domain}/.well-known/pki-validation/${fileName}")

if [ "$statusFilename" == "301" ]; then
statusFilename=$(curl --write-out %{http_code} --silent --output /dev/null "https://${domain}/.well-known/pki-validation/${fileName}")
fi

if [ "$statusFilename" != "200" ]; then
clear
echo "1.2 Khong the cai duoc ZeroSSL cho ${domain}. Vui long kiem tra Domain da tro ve VPS chua ban nhe."
sleep 5
exit 1
fi


echo -e $csrKey > /etc/nginx/zerossl/${domain}/${domain}.key
echo -e $csrCode > /etc/nginx/zerossl/${domain}/${domain}.csr

#xac thuc
curl --silent --location --request GET "https://my.larvps.com/api/v1/zerossl/verify-domain/${orderId}"
clear
echo
for i in {1..35}; do
echo "${i}. Dang cho cap SSL: ${domain}. Vui long doi..."
status=$(curl --silent --location --request GET "https://my.larvps.com/api/v1/zerossl/order-status/${orderId}" | jq ".status" | tr -d '"')
sleep 2
if [[ "$status" == "issued" ]]; then
    #download
    curl --silent --location --request GET "https://my.larvps.com/api/v1/zerossl/${orderId}/download" -o download.txt
    clear
    echo "Da cap thanh cong cho domain: ${domain}".
    sleep 2
    break
fi

if [[ "$i" = "30" ]]; then
clear
echo
echo "Ban vui long doi trong 30 phut roi cap lai, ZeroSSL da ghi nhan dang ky domain cua ban."
echo "Trong thoi gian cho doi. Ban co the cap Let's Encrypt o module 31.2 de site co the hoat dong binh thuong."
sleep 15
exit 1 
fi

done

fi


crtCode=$(cat download.txt | jq '."certificate.crt"' | tr -d '"')
caCode=$(cat download.txt | jq '."ca_bundle.crt"' | tr -d '"')


if [[ "$crtCode" = "" ]]; then
exit 1
echo "Doman hien tai khong cap dc SSL"
sleep 5

fi

echo -e "$crtCode$caCode" > "/etc/nginx/zerossl/${domain}/${domain}.crt"


#save config
cat > "/etc/nginx/zerossl/${domain}/${domain}.conf" <<END
domain=${domainOrder}
expires=${expires}
END

#restore nginx
rm -rf /etc/nginx/conf.d/$domain.conf
username=${domain//[-._]/}
port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
if [[ "$laravel" = "1" ]]; then
. /etc/larvps/menu/action/domain/template/nginx_zerossl_laravel $domain $username $port_listen
else
. /etc/larvps/menu/action/domain/template/nginx_zerossl $domain $username $port_listen
fi
/bin/systemctl restart nginx
