#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "2. Quan ly ZeroSSL"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/articles/huong-dan-su-dung-zerossl-cap-free-ssl-trong-larvps"
echo "/-----------------------------------------------------------------------/"
echo

echo
choose_domain

if [ "$domain" = "" ]; then
    clear
    echo "Ban chua nhap Domain."
    echo
    action_zero_ssl
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain ban nhap khong dung dinh dang."
    echo
    action_zero_ssl
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    echo
    action_zero_ssl
fi
username=${domain//[-._]/}

if [[ ! -d "/root/.acme.sh" ]]; then

    read -p "Nhap Email chinh cua ban (chinh xac): " email
    if [[ ${email} == 0 ]] || [[ ${email} == "" ]]; then
        echo "Vui long nhap Email"
        sleep 5
        action_zero_ssl
    fi
       
    wget -O -  https://get.acme.sh | sh -s email="${email}"
    source  ~/.bashrc


    sed -i "/AUTO_UPGRADE=/d" /root/.acme.sh/account.conf
    echo 'AUTO_UPGRADE=1' >> /root/.acme.sh/account.conf

    mkdir -p /etc/nginx/ssl
    openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048

    cat > "/etc/nginx/ssl_config.conf" <<END
ssl_session_cache shared:SSL_LET:10m;
ssl_session_timeout  10m;
ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
ssl_ecdh_curve secp384r1;
ssl_prefer_server_ciphers on;
ssl_session_tickets off;
resolver 8.8.8.8 valid=300s;
resolver_timeout 5s;
ssl_dhparam /etc/nginx/ssl/dhparam.pem;
END
fi

/root/.acme.sh/acme.sh --set-default-ca --server zerossl

mkdir -p "/home/$username/$domain/public_html/.well-known/acme-challenge"
is_subdomain ${domain}

if [[  "${IS_SUBDOMAIN}" = "n" ]]; then
    /root/.acme.sh/acme.sh --issue -d ${domain} -d www.${domain} --webroot /usr/share/nginx/html --force
else
    /root/.acme.sh/acme.sh --issue -d ${domain} --webroot /usr/share/nginx/html --force
fi


rm -rf /etc/nginx/conf.d/$domain.conf
username=$(get_user $domain)
port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
. /etc/larvps/menu/action/domain/template/nginx_zerossl $domain $username $port_listen



laravel=0
#check Laravel
if [[ -f /home/${username}/${domain}/public_html/public/index.php ]]; then
laravel=1
fi


if [[ "$laravel" = "1" ]]; then
. /etc/larvps/menu/action/domain/template/nginx_zerossl_laravel $domain $username $port_listen
else
. /etc/larvps/menu/action/domain/template/nginx_zerossl $domain $username $port_listen
fi

# restart
restart_nginx 

action_zero_ssl


