#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "2. Quan ly ZeroSSL"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/articles/huong-dan-su-dung-zerossl-cap-free-ssl-trong-larvps"
echo "/-----------------------------------------------------------------------/"
echo

echo
choose_domain

if [ "$domain" = "" ]; then
    clear
    echo "Ban chua nhap Domain."
    echo
    action_zero_ssl
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain ban nhap khong dung dinh dang."
    echo
    action_zero_ssl
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    echo
    action_zero_ssl
fi
username=${domain//[-._]/}

mkdir -p "/home/${username}/${domain}/public_html/.well-known/pki-validation"
. /etc/larvps/menu/action/zero_ssl/create_template $domain

clear
echo "Kiem tra trang thai Http Status Code:"
echo
statusCode=$(curl -H 'Pragma: no-cache' --write-out %{http_code} --silent --output /dev/null "http://${domain}")
echo "http://${domain}: (${statusCode})"
statusCode=$(curl -H 'Pragma: no-cache' --write-out %{http_code} --silent --output /dev/null "https://${domain}")
echo "https://${domain}: (${statusCode})"
is_subdomain "$domain"
if [[ $IS_SUBDOMAIN = "n" ]]; then
statusCode=$(curl -H 'Pragma: no-cache' --write-out %{http_code} --silent --output /dev/null "http://www.${domain}")
echo "http://www.${domain}: (${statusCode})"
statusCode=$(curl -H 'Pragma: no-cache' --write-out %{http_code} --silent --output /dev/null "https://www.${domain}")
echo "https://www.${domain}: (${statusCode})"
fi
echo
echo "Luu y:"
echo "Neu code la 000 (die). Ban vui long kiem tra WWW da tro CNAME ve root domain chua nhe. Sau do thu lai."
echo "Huong dan: https://larvps.com/articles/huong-dan-su-dung-zerossl-cap-free-ssl-trong-larvps"
echo "------------------------------------------"
echo "Da cap SSL thanh cong"
echo "SSL duoc cap la ZeroSSL Premium"
echo "https://${domain}"
echo "------------------------------------------"
echo
echo "Mua SSL Key: https://larvps.com/pages/ssl (SSL tra phi)"
echo "Cam on ban da chon LarVPS lam cong cu quan ly VPS."
echo
sleep 10
action_zero_ssl
