#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "2. Quan ly ZeroSSL > Redirect 301"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/articles/huong-dan-su-dung-zerossl-cap-free-ssl-trong-larvps"
echo "/-----------------------------------------------------------------------/"
echo

echo
choose_domain

if [ "$domain" = "" ]; then
    clear
    echo "Ban chua nhap Domain."
    echo
    action_zero_ssl
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain ban nhap khong dung dinh dang."
    echo
    action_zero_ssl
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    echo
    action_zero_ssl
fi

username=${domain//[-._]/}

read -p "Nhap domain ban muon Redirect: " domain_redirect

. /etc/larvps/menu/action/domain/template/nginx_zerossl_redirect $domain $username $domain_redirect

restart_nginx
echo
action_zero_ssl