#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions

if [[ ! -d /etc/nginx/zerossl/ ]]; then
exit
fi

for domain in `ls -A /etc/nginx/zerossl/`; do

if [[ -f /etc/nginx/zerossl/${domain}/${domain}.conf ]]; then
expires=$(cat /etc/nginx/zerossl/${domain}/${domain}.conf | grep "expires" | cut -f2 -d"=")
domain_list=$(cat /etc/nginx/zerossl/${domain}/${domain}.conf | grep "domain" | cut -f2 -d"=")
days30=$(date --date="30 days" +%Y-%m-%d)

# neu domain het han
if [[ "$days30" > "$expires" ]]; then
. /etc/larvps/menu/action/zero_ssl/create_template "$domain_list"
fi
fi

done