#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "2. Quan ly ZeroSSL > Restore Nginx cua ZeroSSL"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/articles/huong-dan-su-dung-zerossl-cap-free-ssl-trong-larvps"
echo "/-----------------------------------------------------------------------/"
echo

echo
choose_domain

if [ "$domain" = "" ]; then
    clear
    echo "Ban chua nhap Domain."
    echo
    action_zero_ssl
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain ban nhap khong dung dinh dang."
    echo
    action_zero_ssl
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    echo
    action_zero_ssl
fi

username=${domain//[-._]/}

laravel=0
#check Laravel
if [[ -f /home/${username}/${domain}/public_html/public/index.php ]]; then
laravel=1
fi

#restore nginx
rm -rf /etc/nginx/conf.d/$domain.conf
username=${domain//[-._]/}
port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
if [[ "$laravel" = "1" ]]; then
. /etc/larvps/menu/action/domain/template/nginx_zerossl_laravel $domain $username $port_listen
else
. /etc/larvps/menu/action/domain/template/nginx_zerossl $domain $username $port_listen
fi
restart_nginx

echo
action_zero_ssl