#!/bin/bash
. /etc/larvps/menu/functions
echo
echo "==//====================================================================="
echo "31. Chuyen Centos 8 sang AlmaLinux"
echo "/-----------------------------------------------------------------------/"
echo
cd

# kiểm tra centos 8
system_version=$(cat /etc/*-release | grep "VERSION_ID=" | cut -f2 -d'"' | xargs)

if [[ "$system_version" != "8" ]]; then
cat /etc/redhat-release
sleep 6
larvps
fi

echo "Vui long backup lai toan bo du lieu truoc khi thuc hien"
read -p "Xac nhan chuyen Cento 8 sang AlmaLinux: (y/n)" confirm

if [[ "$confirm" = "y" ]]; then

cat >> /etc/yum.repos.d/mariadb.repo<<EOF
[mariadb]
name = MariaDB
baseurl = https://yum.mariadb.org/10.5/centos8-amd64
module_hotfixes=1
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
EOF


# cat >> /etc/yum.repos.d/CentOS-AppStream.repo<<EOF
# [AppStream]
# name=CentOS-\$releasever - AppStream
# baseurl=http://vault.centos.org/\$contentdir/\$releasever/AppStream/\$basearch/os/
# gpgcheck=1
# enabled=1
# gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
# EOF

# cat >> /etc/yum.repos.d/CentOS-Base.repo<<EOF
# [BaseOS]
# name=CentOS-\$releasever - Base
# baseurl=http://vault.centos.org/\$contentdir/\$releasever/BaseOS/\$basearch/os/
# gpgcheck=1
# enabled=1
# gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
# EOF


cd /etc/yum.repos.d/
sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
sudo dnf install epel-release -y
sudo dnf upgrade -y
curl -O https://raw.githubusercontent.com/AlmaLinux/almalinux-deploy/master/almalinux-deploy.sh
rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux
bash almalinux-deploy.sh

fi
clear

cat /etc/redhat-release 
