#!/bin/bash
echo
echo "==//====================================================================="
echo "1. Quan ly Domain"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#section-5"
echo "/-----------------------------------------------------------------------/"
echo
options=(
    "Danh sach - Domain/SubDomain"
    "Them - Domain/SubDomain"
    "Phuc hoi Nginx Domain/SubDomain"
    "Phuc hoi Nginx Default"
    "Phan quyen han (Chown/Chmod)"
    "Xoa Domain/Subdomain"
    "Mo/Khoa Domain/SubDomain"
    "Cai dat SubFolder cho Domain"
    "Xoa SubFolder cua Domain"
    "Chay website bang IP VPS"
    "Thay doi Domain A sang B"
    )
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/domain/list'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/domain/create'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/domain/restore_nginx'
            ;;
        "${options[3]}")
            '/etc/larvps/menu/action/domain/delete_ip_domain'
            ;;
        "${options[4]}")
            '/etc/larvps/menu/permission'
            ;;
        "${options[5]}")
            '/etc/larvps/menu/action/domain/delete'
            ;;
        "${options[6]}")
            '/etc/larvps/menu/action/domain/suspend'
            ;;
        "${options[7]}")
            '/etc/larvps/menu/action/domain/setup_subfolder'
            ;;
        "${options[8]}")
            '/etc/larvps/menu/action/domain/delete_subfolder'
            ;;
        "${options[9]}")
            '/etc/larvps/menu/action/domain/setup_ip_domain'
            ;;
        "${options[10]}")
            '/etc/larvps/menu/action/domain/change_domain'
            ;;
        *) clear && larvps;;
    esac
done

