#!/bin/bash

echo "===//===================================================================="
echo "2. Quan ly Let's Encrypt"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#section-6"
echo "/-----------------------------------------------------------------------/"
echo
options=(
    "Kiem thu SSL cho Domain"
    "Them/gia han SSL - Domain/SubDomain"
    "Cai dat lai ACME.SH"
    "Chuyen WWW thay Root Domain (abc.com => www.abc.com)"
    "Redirect 301 Domain A sang B"
    "Them Alias Domain"
    "Phuc hoi Nginx cua Let's"
    "Cau hinh ACME.SH"
    )
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/lets_encrypt/test_acme'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/lets_encrypt/create_acme'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/lets_encrypt/restore_acme'
            ;;
        "${options[3]}")
            '/etc/larvps/menu/action/lets_encrypt/www'
            ;;
        "${options[4]}")
            '/etc/larvps/menu/action/lets_encrypt/redirect'
            ;;
        "${options[5]}")
            '/etc/larvps/menu/action/lets_encrypt/alias_ssl'
            ;;
        "${options[6]}")
            '/etc/larvps/menu/action/lets_encrypt/restore'
            ;;
        "${options[7]}")
            '/etc/larvps/menu/action/lets_encrypt/config_acme'
            ;;
        *) larvps;;
    esac
done