#!/bin/bash
. /etc/larvps/menu/functions
echo
echo "==//====================================================================="
echo "7. Quan ly Nginx - $(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#section-33"
echo "/-----------------------------------------------------------------------/"
echo
options=(
    "Cau hinh nginx.conf"
    "Cau hinh domain.conf"
    "Them danh sach Referrer Spam"
    "Cau hinh Referrer cho Domain"
    "Chan Ip"
    "Xem Access Log"
    "Tat va Xoa Access Log"
    )
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/nginx_manager/nginx_conf'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/nginx_manager/domain_conf'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/nginx_manager/referrer_spam'
            ;;
        "${options[3]}")
            '/etc/larvps/menu/action/nginx_manager/referrer_domain'
            ;;
        "${options[4]}")
            '/etc/larvps/menu/action/nginx_manager/deny_ip'
            ;;
        "${options[5]}")
            '/etc/larvps/menu/action/nginx_manager/access_log_on'
            ;;
        "${options[6]}")
            '/etc/larvps/menu/action/nginx_manager/access_log_off'
            ;;
        *) larvps;;
    esac
done