#!/bin/bash

echo "===//===================================================================="
echo "2. Quan ly ZeroSSL Premium"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#section-6"
echo "/-----------------------------------------------------------------------/"
echo
options=(
    "Cai dat ZeroSSL"
    "Chuyen WWW thay Root Domain (abc.com => www.abc.com)"
    "Redirect 301 Domain A sang B"
    "Phuc hoi Nginx cua ZeroSSL"
    "Cai dat lai ACME.sh"
    )
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
    	"${options[0]}")
    	    '/etc/larvps/menu/action/zero_ssl/create'
    	    ;;
        "${options[1]}")
            '/etc/larvps/menu/action/zero_ssl/www'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/zero_ssl/redirect'
            ;;
        "${options[3]}")
            '/etc/larvps/menu/action/zero_ssl/restore'
            ;;
        "${options[4]}")
            '/etc/larvps/menu/action/zero_ssl/setup'
            ;;
        *) larvps;;
    esac
done